language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

  
before_script:
  - composer self-update
  - composer install --dev
  - mysql -e 'create database ppdb;'
  - echo "CREATE USER 'ppdb'@'localhost' IDENTIFIED BY 'ppdb';" | mysql -u root
  - echo "GRANT ALL ON ppdb.* TO 'ppdb'@'localhost';" | mysql -u root
  - vendor/bin/doctrine orm:schema-tool:drop --force
  - vendor/bin/doctrine orm:schema-tool:create

script:
  - cd application/tests/
  - ../../vendor/phpunit/phpunit/phpunit --coverage-text
  
after_script:
  - cd ../..
  - php vendor/bin/coveralls -v
