language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - 7
  
before_script:
  - composer install
  - mysql -e 'create database ppdb;'
  - echo "CREATE USER 'ppdb'@'localhost' IDENTIFIED BY 'ppdb';" | mysql -u root
  - echo "GRANT ALL ON ppdb.* TO 'ppdb'@'localhost';" | mysql -u root
  - vendor/bin/doctrine orm:schema-tool:drop --force
  - vendor/bin/doctrine orm:schema-tool:create
  - cd application/tests/
  
script:
  - phpunit #default test command
