<?php



/**
 * AdminRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepo extends Doctrine\ORM\EntityRepository
{
    public function getData(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->addSelect('a')->from('AdminEntity', 'a');
        $qb->orderBy('a.username', 'ASC');
        $query = $qb->getQuery();
        $result =  $query->getResult();
        return $result;
    }
}
