<?php



/**
 * CounterRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepo extends Doctrine\ORM\EntityRepository
{
    public function getData($date = null){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->addSelect('c')->from('CounterEntity', 'c');
        if(!is_null($date)){
            $qb->where('c.date = :date');
        }
        $qb->orderBy('c.date', 'DESC');
        if(!is_null($date)){
            $qb->setParameter('date', $date);
        }
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
