<?php



/**
 * PaymentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepo extends Doctrine\ORM\EntityRepository
{
    public function getData(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->addSelect('y')->from('PaymentEntity', 'y');
        $qb->orderBy('y.paymentDate', 'DESC');
        $query = $qb->getQuery();
        $result =  $query->getResult();
        return $result;
    }
}
