<?php



/**
 * RegistrantRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrantRepo extends Doctrine\ORM\EntityRepository
{
    public function getData($sex = null){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->addSelect('r')->from('RegistrantEntity', 'r');
        if(!is_null($sex)){
            $qb->where('r.sex = :sex');
        }
        $qb->orderBy('r.id', 'ASC');
        if(!is_null($sex)){
            $qb->setParameter('sex', $sex);
        }
        $query = $qb->getQuery();
        $result =  $query->getResult();
        return $result;
    }
}
